In [2]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib as plt
import scipy 
from scipy import stats
import seaborn as sns
from matplotlib.colors import ListedColormap
import os
import re

/Users/mikayla/.pyenv/versions/3.13.5/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
path = kagglehub.dataset_download("tanishksharma9905/top-popular-anime")

print("Path to dataset files:", path)

Path to dataset files: /Users/mikayla/.cache/kagglehub/datasets/tanishksharma9905/top-popular-anime/versions/1

In [4]:
file = os.path.join(path, 'popular_anime.csv')

In [5]:
print("Looking for file:", file)
print("File exists?", os.path.exists(file))

Looking for file: /Users/mikayla/.cache/kagglehub/datasets/tanishksharma9905/top-popular-anime/versions/1/popular_anime.csv
File exists? True

In [6]:
data = pd.read_csv('/Users/mikayla/.cache/kagglehub/datasets/tanishksharma9905/top-popular-anime/versions/1/popular_anime.csv')
data.head()

,id,name,genres,type,episodes,status,aired_from,aired_to,duration_per_ep,score,scored_by,rank,rating,studios,producers,image,trailer,synopsis
0,52991,Frieren: Beyond Journey's End,"Adventure, Drama, Fantasy",TV,28.0,Finished Airing,2023-09-29T00:00:00+00:00,2024-03-22T00:00:00+00:00,24 min per ep,9.30,676737.0,1.0,PG-13 - Teens 13 or older,Madhouse,"Aniplex, Dentsu, Shogakukan-Shueisha Productio...",https://cdn.myanimelist.net/images/anime/1015/...,https://www.youtube.com/watch?v=ZEkwCGJ3o7M,During their decade-long quest to defeat the D...
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy",TV,64.0,Finished Airing,2009-04-05T00:00:00+00:00,2010-07-04T00:00:00+00:00,24 min per ep,9.10,2223666.0,2.0,R - 17+ (violence & profanity),Bones,"Aniplex, Square Enix, Mainichi Broadcasting Sy...",https://cdn.myanimelist.net/images/anime/1208/...,https://www.youtube.com/watch?v=1ac3_YdSSy0,After a horrific alchemy experiment goes wrong...
2,9253,Steins;Gate,"Drama, Sci-Fi, Suspense",TV,24.0,Finished Airing,2011-04-06T00:00:00+00:00,2011-09-14T00:00:00+00:00,24 min per ep,9.07,1467570.0,3.0,PG-13 - Teens 13 or older,White Fox,"Frontier Works, Media Factory, Kadokawa Shoten...",https://cdn.myanimelist.net/images/anime/1935/...,https://www.youtube.com/watch?v=27OZc-ku6is,Eccentric scientist Rintarou Okabe has a never...
3,38524,Attack on Titan Season 3 Part 2,"Action, Drama, Suspense",TV,10.0,Finished Airing,2019-04-29T00:00:00+00:00,2019-07-01T00:00:00+00:00,23 min per ep,9.05,1700946.0,4.0,R - 17+ (violence & profanity),Wit Studio,"Production I.G, Dentsu, Mainichi Broadcasting ...",https://cdn.myanimelist.net/images/anime/1517/...,https://www.youtube.com/watch?v=hKHepjfj5Tw,Seeking to restore humanity's diminishing hope...
4,28977,Gintama Season 4,"Action, Comedy, Sci-Fi",TV,51.0,Finished Airing,2015-04-08T00:00:00+00:00,2016-03-30T00:00:00+00:00,24 min per ep,9.05,264260.0,5.0,PG-13 - Teens 13 or older,Bandai Namco Pictures,"TV Tokyo, Aniplex, Dentsu",https://cdn.myanimelist.net/images/anime/3/720...,NaN,"Gintoki, Shinpachi, and Kagura return as the f..."

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28825 entries, 0 to 28824
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               28825 non-null  int64
 1   name             28825 non-null  object
 2   genres           22756 non-null  object
 3   type             28738 non-null  object
 4   episodes         28046 non-null  float64
 5   status           28825 non-null  object
 6   aired_from       27870 non-null  object
 7   aired_to         10930 non-null  object
 8   duration_per_ep  28825 non-null  object
 9   score            18599 non-null  float64
 10  scored_by        18599 non-null  float64
 11  rank             21962 non-null  float64
 12  rating           28101 non-null  object
 13  studios          16936 non-null  object
 14  producers        13452 non-null  object
 15  image            28825 non-null  object
 16  trailer          5474 non-null   object
 17  synopsis         23457 non-null  object
dtypes: float64(4), int64(1), object(13)
memory usage: 4.0+ MB

In [10]:
data[data['genres'].apply(lambda x: 'Action' in x if isinstance(x, list) else False)]

Empty DataFrame
Columns: [id, name, genres, type, episodes, status, aired_from, aired_to, duration_per_ep, score, scored_by, rank, rating, studios, producers, image, trailer, synopsis]
Index: []

In [ ]:
data = data.drop(['image', 'trailer', 'synopsis'], axis=1)

In [ ]:
data.info()

In [ ]:
def convertDuration(duration):
    if not isinstance(duration, str):
        return None
    
    # remove 'per ep'
    duration = duration.replace('per ep', '').strip()
    
    # match hours & minutes
    hr_match = re.search(r'(\d+)\s*hr', duration)
    min_match = re.search(r'(\d+)\s*min', duration)
    
    totalMinutes = 0
    if hr_match:
        totalMinutes += int(hr_match.group(1)) * 60
    if min_match:
        totalMinutes += int(min_match.group(1))
    
    # if nothing was parsed, pass None
    return int(totalMinutes) if totalMinutes > 0 else None

In [ ]:
data['duration_per_ep'] = data['duration_per_ep'].apply(convertDuration)

In [ ]:
data.head(10)

In [ ]:
data.describe()

In [ ]:
data = data.drop_duplicates()

In [ ]:
data = data.dropna()

In [ ]:
data.to_csv('popularAnime.csv')